functionsDirectory = "D:\\Software Projects\\Road Mgmt-Supabase\\netlify\\functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "D:\\Software Projects\\Road Mgmt-Supabase\\deploy"
publishOrigin = "config"
functions = "D:\\Software Projects\\Road Mgmt-Supabase\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]